import numpy as np
import pandas as pd
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix, roc_auc_score
from xgboost import XGBClassifier

# 1. Load the preprocessed matrices generated by preprocess.py
X_train = np.load('data/processed/X_train.npy')
X_test = np.load('data/processed/X_test.npy')

y_train = pd.read_csv('data/processed/y_train.csv')['label'].values
y_test = pd.read_csv('data/processed/y_test.csv')['label'].values

# 2. Initialize the XGBoost classifier
model = XGBClassifier(
    n_estimators=10000,  
    learning_rate=0.1,  
    max_depth=5, 
    subsample=0.8, 
    objective='binary:logistic',  
    tree_method='hist', 
    device='cuda', 
    early_stopping_rounds=50 
)
print("Training model...")
model.fit(
    X_train, 
    y_train,
    eval_set=[(X_test, y_test)],
    verbose=50
)

# 4. Generate predictions and probabilities
predictions = model.predict(X_test)
probabilities = model.predict_proba(X_test)[:, 1]

# 5. Calculate Metrics
accuracy = accuracy_score(y_test, predictions)
classification_rep = classification_report(y_test, predictions, target_names=['Normal (0)', 'Anomaly (1)'])
confusion_mat = confusion_matrix(y_test, predictions)
roc_auc = roc_auc_score(y_test, probabilities)
print("\n--- Evaluation Results ---")
print("Test set accuracy:", accuracy)
print("ROC AUC score:", roc_auc)
print("\nClassification report:\n", classification_rep)
print("Confusion matrix:\n", confusion_mat)

# 6. Feature Importance and Saving
print("\nWeights of the model:", model.get_booster().get_score(importance_type='weight'))

# Save the model for the Streamlit dashboard and SHAP explainability
model.save_model('xgboost_model.json')
print("\nModel saved successfully as 'xgboost_model.json'")